### ISSUE TITLE
Feature Request: add airflow sensors for furnace and air handler

### ISSUE THREAD

**Issue by wirecuttr** [apetrycki/daikinskyport#100]
Looking to add airflow sensors: ctIFCIndoorBlowerAirflow and ctAHCurrentIndoorAirflow.
Based on the ha-daikinone integration looks like they cane be used as-is: https://github.com/zlangbert/ha-daikinone/blob/main/custom_components/daikinone/daikinone.py

**Comment by wirecuttr** [comment]
the furnace airflow seems to be working. I can't test the air handler airflow as I do not have an air handler.

**Comment by paulcarlucci** [comment]
I have a heat pump and I'm running wirecuttr's branch.  Airflow looks good to me.
