### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by jf-navica** [apetrycki/daikinskyport#102]
Possible issue, just want to make sure...  I stumbled upon https://www.daikinone.com/openapi/documentation/index.html
They mention to limit requests to every 3 minutes.  However, the only thing I find is sleep(3), which is 3 seconds.  Is there another delay somewhere?

Thanks!

**Comment by apetrycki** [comment]
This integration doesn't use the OpenAPI.  So far only one person had an issue and it seems to be resolved now.

**Comment by jf-navica** [comment]
The question remains, just to make sure we're not spamming Daikin with requests...  Just trying to find the logic behind the polling
