### ISSUE TITLE
is_aux_heat is deprecated in latest HA beta

### ISSUE THREAD

**Issue by dualtronic** [apetrycki/daikinskyport#104]
Error and versions below:

Core 2024.4.0b3
Supervisor 2024.03.1
Operating System 12.2.rc1
Frontend 20240329.1

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:419
integration: Climate ([documentation](https://rc.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))

**`daikinskyport::Thermostat implements the `is_aux_heat` property or uses the auxiliary heater methods in a subclass of ClimateEntity which is deprecated and will be unsupported from Home Assistant 2024.10. Please create a bug report at https://github.com/apetrycki/daikinskyport/issues`**

**Comment by whitema** [comment]
2024.4.0 has released and this bug exists.

The daikinskyport custom integration is using deprecated climate auxiliary heater
This stops working in version 2024.10.0. Please address before upgrading.
The custom integration daikinskyport implements the is_aux_heat property or uses the auxiliary heater methods in a subclass of ClimateEntity.

Please create a bug report at https://github.com/apetrycki/daikinskyport/issues.

Once an updated version of daikinskyport is available, install it and restart Home Assistant to fix this issue.

**Comment by jf-navica** [comment]
Discussions on this issue there:  https://github.com/home-assistant/architecture/discussions/932

Seems Ecobee hasn't changed either yet...  https://github.com/home-assistant/core/blob/2024.4.1/homeassistant/components/ecobee/climate.py

**Comment by apetrycki** [comment]
I updated to include an aux heat switch and removed the aux_heat stuff from the climate entity.

**Comment by jf-navica** [comment]
Thanks for the update!  I still hope Frenck will consider adding aux as a heating mode so everything is integrated in the climate tile.

**Comment by EdjoSadowski** [comment]
I updated to v1.0.0, rebooted HA and still get the "This stops working in version 2024.10.0. Please address before upgrading. The custom integration daikinskyport implements the is_aux_heat property or uses the auxiliary heater methods in a subclass of ClimateEntity." warning

Core: 2024.4.3
Supervisor: 2024.04.0
Operating System: 12.2
Frontend: 20240404.2

**Comment by EdjoSadowski** [comment]
That seemed to have worked 🤞
