### ISSUE TITLE
2024.4.0b3 Ring Doorbell Issue

### ISSUE THREAD

**Issue by capritzl** [apetrycki/daikinskyport#105]
Since upgrading to the 2024.4.0b3 I have lost my Ring Doorbell entity information.  Has anyone else experienced this issue?

See attached image.

![IMG_2900](https://github.com/apetrycki/daikinskyport/assets/76876336/6d6661e5-3c66-40ff-bd10-af924a7169b0)

Core: 2024.4.0b3
Supervisor: 2024.03.1
Operating System: 12.1
Frontend: 20240329.1

**Comment by apetrycki** [comment]
What does this have to do with the Daikin integration?

**Comment by capritzl** [comment]
Sorry.  Thought I was opening a new issue.  I did not realize it was under the Daikin integration.
