### ISSUE TITLE
Power sensor reporting high value when idle

### ISSUE THREAD

**Issue by apetrycki** [apetrycki/daikinskyport#106]
My indoor power is reporting as 920w whenever it is idle.  Since there are other parameters that can be cross-matched to determine is the system is idle is it reasonable to disregard the value reported  just artificially set indoor power to zero when idle?

_Originally posted by @paulcarlucci in https://github.com/apetrycki/daikinskyport/issues/31#issuecomment-2034016926_

**Comment by paulcarlucci** [comment]
Resolved with [PR 108](https://github.com/apetrycki/daikinskyport/pull/108) therefore this can be closed.
