### ISSUE TITLE
[Discussion] Look in to using Integration Token

### ISSUE THREAD

**Issue by LeaderbotX400** [apetrycki/daikinskyport#115]
With in the Daikin app if you go `three lines > Cloud Services > Home Intigration` you can get an integration token that can be used in place of your credentials. But it also uses a different api `https://integrator-api.daikinskyport.com` to be exact.

Not sure the differences between this API and the one currently used so this might be worthless

[Integrator API Reference](https://www.daikinone.com/openapi/index.html)

**Comment by apetrycki** [comment]
I've looked into that API before. It has much less information and functionality. The current integration also uses a token generated after first login. There are instances when that token gets revoked and that's the only real time it uses the username and password again. It usually seems to occur when they update something on the backend.
