### ISSUE TITLE
Fan control doesn’t work

### ISSUE THREAD

**Issue by JakeScheck** [apetrycki/daikinskyport#118]
I have successfully connected my system to home assistant, and basic thermostat setpoint control works. Mode control from within Home Assistant seems to work, but reading of mode if changed elsewhere does not work.

Most importantly, fan control does not work - if I change fan speed in Home Assistant it simply changes back to On. If I change it in my Daikin thermostat settings it does not change anything in home assistant. 

If there are any specific details about my system that would be helpful in troubleshooting this please let me know.

**Comment by JakeScheck** [comment]
I imagine there’s something hardware specific but the 1.1.0 update did not fix either of the issues I described.

**Comment by apetrycki** [comment]
Make sure you do a full refresh of your browser/app. I noticed when I was working on it that it didn't seem to change until I refreshed my browser. If you make setting changes elsewhere, it won't refresh in HA until the next polling cycle.
