### ISSUE TITLE
Incomplete Integration

### ISSUE THREAD

**Issue by dph5087** [apetrycki/daikinskyport#120]
I have 4 Daikin One Lite Thermostats and 1 Daikin One Touch thermostat connected to 5 Daikin FTXRxxxxxxx Indoor mini split units. Your integration is able to discover the 5 thermostats, along with weather and switch entities, however I don't see any sensor entities. Also the weather entities for the Daikin One Lite always read 261 degrees F.

**Comment by apetrycki** [comment]
Are you using the main integration or the experimental One Lite?  I'm still working on the One Lite, so it's not in the mainline yet.

**Comment by dph5087** [comment]
The main integration as far as I know. Should I be trying the experimental one? If so, where can I find it?

**Comment by apetrycki** [comment]
Yeah, you have to use https://github.com/apetrycki/daikinskyport/tree/onelite

Let me know if you have any issues when using that instead.

**Comment by dph5087** [comment]
![Xnip2024-07-17_22-55-39](https://github.com/user-attachments/assets/87ed7afa-795c-4124-a35d-81b7a62126df)
This is probably me being a noob at this, but when I use that custom repository URI it seems to install the main one.

**Comment by dph5087** [comment]
![Xnip2024-07-17_22-58-18](https://github.com/user-attachments/assets/a125c4a7-d2e0-49d9-b68e-412ed251ed00)
And here's what I see on my dashboard

**Comment by apetrycki** [comment]
let me know if you're still having issues with the latest release

**Comment by apetrycki** [comment]
It's been a week without a response, so I'm assuming this is no longer an issue.

**Comment by dph5087** [comment]
It's working perfectly now! With one click I can update the settings for 4
Daikin One Lites and 1 Daikin One Touch. Thank you for all your efforts!
