### ISSUE TITLE
Service daikinskyport.daikin_set_fan_schedule service does not work

### ISSUE THREAD

**Issue by knightjoel** [apetrycki/daikinskyport#13]
When calling the `daikinskyport.daikin_set_fan_schedule` service using the example data provided, the call errors out. The following is logged in home-assistant.log:

```
2021-06-29 15:04:45 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['end_time']
2021-06-29 15:04:45 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140177542335216] Error handling message: extra keys not allowed @ data['end_time']. Got None
```

Removing `end_time` from the service call data field results in a successful call. However, the fan schedule still does not appear to be set.

- [ ] Fix the script error on input data
- [ ] Diagnose why the service call does not modify the thermostat's fan schedule

**Comment by apetrycki** [comment]
I found the reason for that error.  It was a typo. ATTR_FAN_STOP_TIME = "end_time", not "stop_time".  Having another issue now.

**Comment by apetrycki** [comment]
OK, I think it's working with my changes.  Note that you have to set the fan to "Schedule" under your thermostat for the schedule to be used.  I realized I should have also added the fan speed (fanCirculateSpeed) as an option in the service, so I'll do that now then update the repo.

**Comment by apetrycki** [comment]
I updated the repo.  It works for me, so let me know if you have the same success and I'll close this out.

**Comment by apetrycki** [comment]
I'm assuming this works now, so closing the issue
