### ISSUE TITLE
Version format in manifest is not good

### ISSUE THREAD

**Issue by jf-navica** [apetrycki/daikinskyport#15]
As per https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions, version needs major, minor and patch version. For example, "1.0.0"

Current version "0.1" raises a warning in the logs.

**Comment by apetrycki** [comment]
I'll fix this in my next commit.  I'm making a few changes to fix some things.

**Comment by apetrycki** [comment]
Changed to 0.1.0
