### ISSUE TITLE
Get rid of time on weather forecast

### ISSUE THREAD

**Issue by knightjoel** [apetrycki/daikinskyport#26]
This is trickier than I thought it might be. The [HA frontend has a condition](https://github.com/home-assistant/frontend/blob/797f60d725bd546f519a23617e5f57539813d7a6/src/dialogs/more-info/controls/more-info-weather.ts#L182-L191) that looks to see if a "low temperature" value is present in the forecast data. If it's not, the frontend assumes the forecast is an hourly forecast and formats the datetime with time included.

The problem of course is the skyport API doesn't return a low temperature.

Possible ways forward:

1. Submit a PR for the HA frontend which makes it possible to display a daily forecast without a low temperature
2. Send a dummy low temperature (maybe just set it to the high temperature?) from daikinskyport to trick the frontend into showing a daily forecast

**Comment by apetrycki** [comment]
Looks like this has been fixed
