### ISSUE TITLE
ctOutdoorNoofHeatStates key not in JSON returned from the API

### ISSUE THREAD

**Issue by flyingmoose1** [apetrycki/daikinskyport#27]
Climate entity fails to initialize due to the ctOutdoorNoofHeatStates key not being in the JSON returned from the API. From Home Assistant log:

```Logger: homeassistant.components.climate
Source: custom_components/daikinskyport/climate.py:377
Integration: Climate (documentation, issues)
First occurred: 4:34:42 PM (1 occurrences)
Last logged: 4:34:42 PM

Error while setting up daikinskyport platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/daikinskyport/climate.py", line 213, in setup_platform
    devices = [
  File "/config/custom_components/daikinskyport/climate.py", line 214, in <listcomp>
    Thermostat(data, index)
  File "/config/custom_components/daikinskyport/climate.py", line 377, in __init__
    if self.thermostat["ctSystemCapEmergencyHeat"] or (self.thermostat["ctOutdoorNoofHeatStates"] > 0):
KeyError: 'ctOutdoorNoofHeatStates'
```

This is a Daikin One+ thermostat. I can get the outdoor unit model if needed.

**Comment by apetrycki** [comment]
Can you use the info in https://github.com/apetrycki/daikinskyport/blob/master/API_info.md to get the output of your thermostat and attach it here?  Your final command should look like this:
```
curl --location --request GET "https://api.daikinskyport.com/deviceData/<UUID of device>" \
--header "Accept: application/json" \
--header "Authorization: Bearer <access token>"
```

Do you have heat in your system?  Including the model of your indoor and outdoor units might be helpful as well so I can take a look at specs.

**Comment by flyingmoose1** [comment]
Sure, I put it in a gist since the output was over 2000 lines long: https://gist.github.com/flyingmoose1/73d593171cf667e22367ab9d7e05ca2f

I have heat and cooling. The outdoor unit is a 5MXS48TVJU, and the indoor unit is a FFQ18Q2VJU. 

The thermostat interfaces with a Daikin One+ Translation adapter (https://daikinone.com/smart_thermostats/oneplus/pros/IOD-7134.pdf) which then interfaces with the indoor unit over P1/P2. I wonder if this is the hangup?

**Comment by apetrycki** [comment]
Like I thought, your system doesn't report a ctOutdoorNoofHeatStages.  It also shows ctSystemCapEmergencyHeat as false.  I'll need to figure out a different way to determine if heat is available.

It could be the translation adapter.  I'm not really sure exactly what it does.  I'm guessing it adapts the protocol for units it wasn't designed for.  Seems like it would be easier to do in software unless the voltage is different or something.  

I'll update when I figure something out.

**Comment by apetrycki** [comment]
Looks like that was my error.  It should be ctOutdoorNoofHeatStages and I have it written as ctOutdoorNoofHeatStates in the code.  Your thermostat is not reporting the number of stages, though.  It doesn't report a lot of things, so my assumption about the translator is probably correct.  The code should work after I change States to Stages, but it looks like I should still find a better way to determine if heating is available.

**Comment by flyingmoose1** [comment]
I made the change locally, and that did indeed fix my issue. Thank you for fixing!

**Comment by apetrycki** [comment]
I just found the actual value I should be using.  It is ctSystemCapHeat.  Please update one more time with the new code and let me know if it still works.

**Comment by flyingmoose1** [comment]
That works as well after updating to the new code. Thanks again!

**Comment by apetrycki** [comment]
Awesome, glad we were able to figure it out.
