### ISSUE TITLE
climate.fan_mode always set to on instead of high, medum, or low when circulation is on

### ISSUE THREAD

**Issue by tlykken** [apetrycki/daikinskyport#32]
Looking at my climate state, even though the valid fan modes are as follows:

```
fan_modes:
  - auto
  - 'on'
  - low
  - medium
  - high
  - Schedule
```

If circulation is enabled, the fan_mode is always on.  I believe this should be set to the speed of the fan, i.e. high, medium or low.

Looking at the return for the daikin api, I believe the proper attribute to use to pull for this is 'fanCirculateSpeed'.   While pulling, the number represented is 0 = low, 1 = medium, and 2 = high.

**Comment by apetrycki** [comment]
Fixed in the latest
