### ISSUE TITLE
Add support for Scenes

### ISSUE THREAD

**Issue by bravolavo** [apetrycki/daikinskyport#37]
When daikinskyport is added to a Scene, the scene fails to execute. Two pop-up errors occur:

Failed to call service scene/apply

Failed to call service scene/turn_on

**Comment by apetrycki** [comment]
Reference for implementation: https://developers.home-assistant.io/docs/reproduce_state_index

**Comment by apetrycki** [comment]
It looks like this should work with the changes they've made to HA.  Can you see if it does what you need it to @bravolavo?
