### ISSUE TITLE
FR: Add thermostat settings as sensors

### ISSUE THREAD

**Issue by hume-github** [apetrycki/daikinskyport#40]
I believe the current heating/cooling thresholds are contained in hspActive and cspActive, and the daikin class parses them.

By adding them in among the sensor values, not only can you have a thermostat display (despite the integration not being two-way), you can do something like comparing the outside temperature to the the thermostat setting to get a delta, and from there combine it with the reported energy usage to get a heating-degree-hour (I believe it's called that, I'm not an HVAC guy...) to get a rough estimate of your house's heating/cooling efficiency.

**Comment by apetrycki** [comment]
These are stored as attributes in the climate entity.  You can create sensors from those or use the attributes directly in automations.
https://community.home-assistant.io/t/using-attribute-as-trigger-for-automation/124665
https://community.home-assistant.io/t/attribute-as-sensor/149170
