### ISSUE TITLE
Pairing with the app appears to be different than Skyport

### ISSUE THREAD

**Issue by kylewilliams321** [apetrycki/daikinskyport#44]
I came here from home assistant forum but it does appear me and at least 2 others have similar issues. My thermostat is paired with my mobile app. But when I pass my credentials in to HA config file nothing happens. There is no entity that matches my thermostat name. I did a little googling and stumbled across skyport Daikin and there didn’t appear to be an account for my setup. So I created one. But, there is no linkage. I can add my thermostat but from what I can tell I’d have to remove it from my phone app and I’m not willing to do that. Thoughts?

**Comment by apetrycki** [comment]
Can you use the steps here: https://github.com/apetrycki/daikinskyport/blob/master/API_info.md
to see if you can get any information or errors from the API?

**Comment by kylewilliams321** [comment]
I might be doing this wrong, not 100% familiar with curl and the syntax... but I did download the version and it appears to be working correctly.  However, when I run the first command

 

curl --location --request POST https://api.daikinskyport.com/users/auth/login ^

--header "Accept: application/json" ^

--header "Content-Type: application/json" ^

--data '{"email": "<email>", "password": "<password>"}'

 

(I changed \ to ^ based on my research running curl in windows...

 

I plug in in my credentials I get

 

" {"message": "Invalid request body"}curl: (6) Could not resolve host: [gmail.com](http://gmail.com/),

curl: (3) URL using bad/illegal format or missing URL

curl: (3) unmatched close brace/bracket in URL position 11:

myPW1234}' "

**Comment by apetrycki** [comment]
You can get rid of the ^ and just put everything on the same line.  Instead of putting the ```--data``` part on the line, put ```{"email": "<email>", "password": "<password>"}``` into a file and call the file like ```--data "@daikin.json"```.  That will get rid of any issues with command line formatting.

**Comment by apetrycki** [comment]
Closing due to lack of response.  If you took steps to fix your issue, please leave a comment here so others can get help.  I did see on the HA community forum that someone else had an issue and it started working after a couple days, so there may just be some lag in account creation or something.
