### ISSUE TITLE
History graphs showing wrong temperature set points for 2nd thermostat

### ISSUE THREAD

**Issue by sfskipperjim** [apetrycki/daikinskyport#45]
I'm 3 days into HA, but extreme TIA for the work that has been done already!

I had 2 Fit Heat Pump systems installed and searched for a way to get operating data (like I had previously with my Ecobee's).  Already from what I've seen some of the parameters for my Fit's don't line up with other models, so I expect to be a contributor fairly soon.  But in my newbie state, wondering why after installing my Overview page shows the 2 thermostats with set point and actual temperatures but when I go to the History page only 1 of the thermostats is showing the target temperature.  The other is showing target temperature low/high.  Both thermostats are set the same in cool mode.

I also tried to add my first card to have a less cluttered history graph and the climate entity is presenting the same as the history.  This might not be a daikinskyport issue but no idea where to dig.

**Comment by apetrycki** [comment]
I think you may be the first to have 2 thermostats. Probably a bug. Can you take some screenshots of what you're seeing? Not sure I quite understand.

**Comment by sfskipperjim** [comment]
Attached screenshots hopefully are labeled clearly.

In Overview page the thermostats appeared after installing and running.  Note the reported set temperatures and actual temperatures seem correct.

History page shows too much info so I attempted to make a new card for each thermostat.  As I learn more I'll probably modify with Grafana/InfluxDB.  But you can see that using the Climate entity for each thermostat results in the upstairs displaying high/low set points while the downstairs is using the expected 1 set point.

And now for the history page.  I just opened and was surprised to see it was showing the expected set points for both thermostats.  So I expanded the view to start from yesterday and now the upstairs is again showing high/low
![OverviewPageUpstairsTemperatures](https://user-images.githubusercontent.com/107084559/173188520-51b12d5f-7ddf-4362-b9b3-10d9124f66de.JPG)
![OverviewPageThermostats](https://user-images.githubusercontent.com/107084559/173188521-c8a09cc8-5d50-484f-a11b-33f49fb6dadc.JPG)
![HistoryPageTwoDaysShowingHighLowTargetTemperaturesForUpstairsThermostat](https://user-images.githubusercontent.com/107084559/173188522-443f23e0-7aff-4674-b358-326ddea67486.JPG)
![HistoryPageTodayShowingExpectedTargetTemperaturesForBothThermostats](https://user-images.githubusercontent.com/107084559/173188523-965fde00-be13-415f-a3f0-250ad3e65b68.JPG)
![OverviewPageDownstairsTemperatures](https://user-images.githubusercontent.com/107084559/173188524-2ab70847-6b42-4969-a1ff-5d6ea4216bb2.JPG)
.

**Comment by apetrycki** [comment]
Interesting. Have you ever had the thermostat in auto mode? Maybe that's how history handles that when you've used different settings?

**Comment by sfskipperjim** [comment]
Upon installation both systems were set to Cool only mode (they couldn't commission the heat, will have to wait until fall).  Querying Climate.upstairs I see cool mode for the initial entry 2022-06-08 16:08, then later I remember toggling it to auto and back to cool when I was trying to figure this out.  First toggle 2022-06-09 13:25 and back a couple seconds later.  Second toggle 2022-06-10 16:09 and back at 16:11.

I remember searching and learning that the target high/low set points are only used with hvac_mode set to heat_cool, so I toggled the upstairs to see if it would do anything.  It didn't seem to change the history at the time, hence the issue was opened.

Here is some interesting information.  I just went to the history and if I select the start time of 2022-06-10 12:15 or later I only see target temperature for the upstairs thermostat.  If I start at 12:10 or earlier I see the high/low targets.  Not sure why query times and log times don't match, but seems like maybe the second toggle might have changed something.

I'll continue to check history but it's kind of looking like the upstairs thermostat instance maybe didn't set up correctly.  And potentially points to another issue if settings are changed between auto and cool (or heat?) in the future.

**Comment by sfskipperjim** [comment]
Update - my SD card had errors so I reinstalled 2 days ago with a new/larger card.  No issues with either thermostat or the previously seen incorrect set points for the upstairs.  This is running on a pi 3 B, tomorrow I should receive a pi 400 and will do a clean HA install on the more powerful device.

**Comment by apetrycki** [comment]
Ok, so sounds like this can be closed.  As a note, you want to use a good Endurance grade SD card and also offload all your high transaction stuff to memory as much as possible.  No swap, use RAM disks for tmp and logs, put databases on other media.  You shouldn't have any problems if you do that.

**Comment by sfskipperjim** [comment]
I did have a good card, it was just small and that likely caused an issue.  My plan was to learn this stuff and initially could only use what I had laying around until I could upgrade.  The pi 3B was the newest thing I had (and previously was only using it for genealogy stuff).  Because I'm learning, I was using the HA built image and not trying to set up a container (although that's where I'd rather be).  But your comments unfortunately prompt me to ask if RAM disks are easily setup/changed from HA built image or if I should put the time into running HA in a container.  Thanks.
