### ISSUE TITLE
Integration is overriding deprecated methods

### ISSUE THREAD

**Issue by adwoodworth** [apetrycki/daikinskyport#46]
After upgrade to Home Assistant 2022.7.0, I am logging an error "custom_components.daikinskyport.weather::DaikinSkyportWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom component author."

I am reporting it here.  I suspect it is related to the change of Python version.

**Comment by knightjoel** [comment]
I believe this is related to upcoming changes in HA (https://developers.home-assistant.io/blog/2022/06/27/weather_entity_refactoring/).
