### ISSUE TITLE
save_json from homeassistant.util.json module depreciated

### ISSUE THREAD

**Issue by jasonhurlbert** [apetrycki/daikinskyport#55]
I noticed today in Home Assistant's logs while setting up a new instance of Home Assistant that daikinskyport is using a depreciated (and soon to be removed) module:

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 2:01:33 PM (1 occurrences)
Last logged: 2:01:33 PM

Detected integration that uses save_json from homeassistant.util.json module. This is deprecated and will stop working in Home Assistant 2022.4, it should be updated to use homeassistant.helpers.json module instead. Please report issue to the custom integration author for daikinskyport using this method at custom_components/daikinskyport/__init__.py, line 70: save_json(hass.config.path(DAIKINSKYPORT_CONFIG_FILE), jsonconfig)
```

**Comment by unc2k3** [comment]
> I noticed today in Home Assistant's logs while setting up a new instance of Home Assistant that daikinskyport is using a depreciated (and soon to be removed) module:
> 
> ```
> Logger: homeassistant.helpers.frame
> Source: helpers/frame.py:77
> First occurred: 2:01:33 PM (1 occurrences)
> Last logged: 2:01:33 PM
> 
> Detected integration that uses save_json from homeassistant.util.json module. This is deprecated and will stop working in Home Assistant 2022.4, it should be updated to use homeassistant.helpers.json module instead. Please report issue to the custom integration author for daikinskyport using this method at custom_components/daikinskyport/__init__.py, line 70: save_json(hass.config.path(DAIKINSKYPORT_CONFIG_FILE), jsonconfig)
> ```

This has broken my integration for my Daikin Thermostats as well.  Rolling back to a previous instance until fixed.
