### ISSUE TITLE
Not sure this is working any longer?

### ISSUE THREAD

**Issue by kylewilliams321** [apetrycki/daikinskyport#59]
I used to have this working but then after I lost power in our house for several hours and it was restored the integration wasn't coming up properly. I had it running for months with no issues.
So I did some diagnosing/troubleshooting. One of the first things I tried was logging into the app on my phone. Well I couldn't remember my password so I reset it. And here's maybe the first screw up. Because I reset it I figured well I guess now I just have to update the pw in the config.yaml file. I did that and restarted Home Assistant and still nothing.  So I cam here and I've went through the following steps.
1) I restarted multiple times
2) I re-downloaded and installed the HACS integration
3) I restarted more times
Not really sure what more to do? Thoughts?

**Comment by kylewilliams321** [comment]
Log:
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/daikinskyport/daikinskyport.py:31
Integration: daikinskyport (documentation, issues)
First occurred: 5:16:47 PM (1 occurrences)
Last logged: 5:16:47 PM

Error during setup of component daikinskyport
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 257, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/daikinskyport/__init__.py", line 72, in setup
    data = DaikinSkyportData(hass.config.path(DAIKINSKYPORT_CONFIG_FILE))
  File "/config/custom_components/daikinskyport/__init__.py", line 49, in __init__
    self.daikinskyport = DaikinSkyport(config_file)
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 55, in __init__
    config = config_from_file(config_filename)
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 31, in config_from_file
    return json.loads(fdesc.read())
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

**Comment by apetrycki** [comment]
you probably need to delete your daikinskyport.conf

**Comment by kylewilliams321** [comment]
Yep I tried that as well with no luck. I’ll try again later today and
delete everything again as well as the daikinskyport.conf file (if there).

**Comment by kylewilliams321** [comment]
Update: I've done this multiple times deleting everything including the daikinskyport.conf file and rebooting HA and still not working.  The config.yaml file correctly has my username/pw in there w/ correct spacing.

**Comment by kylewilliams321** [comment]
nm, i got it working now. I actually had the password wrong many times in a row I guess. whoops. dumb me.
