### ISSUE TITLE
2 different temperature entities?

### ISSUE THREAD

**Issue by enkrypt3d** [apetrycki/daikinskyport#61]
I have an interesting one for u, My Daikin thermostats are working fine in HA but I'm trying to figure out what the difference is between "current temp" & "indoor temp"... the "current temp" is odd as it rarely changes. the indoor temp changes quite a lot but the thermostat is only following the current temp which rarely moves if ever. If I could display the "indoor temp" for the thermostat, this would be huge as the AC tends to run way beyond it's setpoint.. I'm guessing the "current temp" is the set point? 
 
![image](https://github.com/apetrycki/daikinskyport/assets/93238214/8bf17f00-8ac9-4bf6-92e2-61e333e2fb04)

**Comment by enkrypt3d** [comment]
no replies on this one either.....=\

**Comment by apetrycki** [comment]
I think this is due to a change in HA.  My revamped version seem to be working correctly.  Current Temperature and the Indoor Temperature both use the same value from the API.
