### ISSUE TITLE
Error connecting to Daikin Skyport while attempting to get thermostat data. Refreshing tokens and trying again.

### ISSUE THREAD

**Issue by daswass** [apetrycki/daikinskyport#65]
Hey - Ive been messing with this for about 3 days and haven't been able to get it working. I ran through all the requests using Postman and and not having any issue querying the devices, but when using this integration, after turning on debug logging, I just keep getting the error in the title. Any thoughts?

**Comment by daswass** [comment]
I removed the **Host** header in Postman and got a 400 response when querying _https://api.daikinskyport.com/devices_. Is it possible that the request made by the python in this add on is missing the **Host** header?

**Comment by daswass** [comment]
Got it! It seemed one of my three thermostats was disconnected from the network. It happened to be the first in the list. Theres a specific error code returned by the API for this. I would suggest handling this error code and moving on rather than assuming the tokens are no good.

**Comment by apetrycki** [comment]
Can you post the response and I'll take a look?

**Comment by daswass** [comment]
`{"message":"DeviceOfflineException"}`

**Comment by apetrycki** [comment]
And you receive that message when you probe the device (curl --location --request GET "https://api.daikinskyport.com/deviceData/<UUID of device>") or when you get the list of devices (curl --location --request GET "https://api.daikinskyport.com/devices")?

**Comment by daswass** [comment]
When probing the device. It seems like the list of devices comes back with all 3 devices, and then querying the first device returns the error.

**Comment by daswass** [comment]
Hey, @apetrycki any updates pending?

**Comment by apetrycki** [comment]
I'm in the middle of a major rewrite. I'm trying to knock out the major issues first, then I'll get to stuff like this. I'm working in the ui_config branch for now.

**Comment by apetrycki** [comment]
Should work in the new version as I merged in your PR.  I haven't taken my thermostat offline to test it.
