### ISSUE TITLE
Forecast deprecated. Transition to new method.

### ISSUE THREAD

**Issue by jlabataille** [apetrycki/daikinskyport#66]
In next beta release, forecast is deprecated. There is a new card for implement forecast feature.

Tested on:
Home Assistant 2023.9.0b0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230830.0 - 

Error message:
The daikinskyport integration is using deprecated forecast
This stops working in version 2024.3.0. Please address before upgrading.
The integration daikinskyport is using the deprecated forecast attribute.

Please report it to the custom integration author..

**Comment by dabbill** [comment]
I got this same message today.

**Comment by BeebleZap** [comment]
Same here. This message came after updating to 2023.9

**Comment by apetrycki** [comment]
Fixed in latest
