### ISSUE TITLE
Parameter List

### ISSUE THREAD

**Issue by TJCoffey** [apetrycki/daikinskyport#7]
I've been working on logging from my Daikin system using an MQTT broker and found the daikinskyport class very useful. I don't know if a full list of parameters (at least from my system) is interesting or useful for this project. If so, it's over at https://github.com/TJCoffey/DaikinSkyportToMQTT/blob/main/ThermostatParameters.md. Most of it is still unknown (or unimplemented on my system, a lot of INT_MAX values in there), but it's a start.

**Comment by apetrycki** [comment]
Thanks for the heads up.  I'll link to your file in the documentation if that's alright.

**Comment by TJCoffey** [comment]
That works. Feel free to do whatever you like with it. A pull request across unrelated projects felt weird and I'm not even sure if that's a thing in git. Just trying to get as much info out there as I can.

**Comment by andyfowler** [comment]
@TJCoffey Thanks for sharing this! I've followed this repo, as a Daikin One+ / Home Assistant enthusiast. I will take a look at your params and see if I can help fill in some blanks (I have a DM96 NG furnace and DX17VSS split AC). Out of curiosity, how are you handling data after it lands in MQTT? Are you saving it to Prometheus?

**Comment by TJCoffey** [comment]
@andyfowler I've got a set of Docker containers running these: https://github.com/Nilhcem/home-monitoring-grafana
Effectively I'm subscribed to home/* on the MQTT broker and logging it to InfluxDB to populate Grafana dashboards. I'm not trying to do any control, and I strongly suspect using MQTT as a middleman is probably a bottleneck if you're trying to actually log all of the data out of the thermostat, so I don't really recommend it. I just already had that part of the pipeline set up so it was an easy way to dump data. If I had already been running home assistant, that might have been the easier path (or directly dumping into Influx).

**Comment by apetrycki** [comment]
I've added a link to the API information to TJCoffey's efforts.
