### ISSUE TITLE
Can't get integration working again..... 

### ISSUE THREAD

**Issue by enkrypt3d** [apetrycki/daikinskyport#70]
After reinstalling the latest code via HACS and manually, I get this error when adding my login info to the config file.... All the files are where they're supposed to be. This was working just fine before but now it's completely broken.

**Comment by enkrypt3d** [comment]
Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:579
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 6:12:29 PM (1 occurrences)
Last logged: 6:12:29 PM

[547997355840] The system cannot restart because the configuration is not valid: Integration error: daikinskyport - Integration 'daikinskyport' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 579, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Integration error: daikinskyport - Integration 'daikinskyport' not found.

**Comment by enkrypt3d** [comment]
I deleted everything, started over fresh. not seeing any errors now but it's showing "unavailable" for all entities....

**Comment by enkrypt3d** [comment]
Any help would be appreciated....

**Comment by apetrycki** [comment]
Not sure what to tell you.  I haven't changed the main branch other than updating the readme.  I'd run through the API commands manually and make sure you're getting the proper responses back.  Maybe the thermostat is offline or something.

**Comment by enkrypt3d** [comment]
the thermostat is working fine in the main daikin One+ app... Deleting
everything installing fresh didn't work... Is there an order of operations
here? Can you expand the instructions? maybe I'm missing something....

Add repo to HACS > click the "download" button > then restart HA? Then add
creds in configuration.yaml? Is that the right order? I'm not seeing any
errors, it's just unavailable ....

**Comment by apetrycki** [comment]
try the new integration and let me know if your problem goes away.  If not, you'll have to get me all your API info for me to look at.

**Comment by enkrypt3d** [comment]
This is with the new integration.....
