### ISSUE TITLE
WARNING Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for daikinskyport doing blocking calls at custom_components/daikinskyport/climate.py, line 414: sleep(3)

### ISSUE THREAD

**Issue by enkrypt3d** [apetrycki/daikinskyport#72]
WARNING (MainThread) [daikinskyport] Could not refresh tokens: 400 Trying to re-request

Just updated thru HACS notification and now it's not working again. 

![image](https://github.com/apetrycki/daikinskyport/assets/93238214/309d2561-285a-41f6-929b-201c5569a05b)

When I try to change the temp it just goes back to what it was....

**Comment by enkrypt3d** [comment]
It appears that it can read the values, it just can't make any changes. really odd.

**Comment by enkrypt3d** [comment]
WARNING (SyncWorker_4) [py.warnings] /config/custom_components/daikinskyport/climate.py:615: RuntimeWarning: coroutine 'DaikinSkyport.make_request' was never awaited
  self.data.daikinskyport.set_permanent_hold(

adding more detail

**Comment by git2021-ll** [comment]
Seeing the same. Saw there was an update in HACS to migrate to Integration from config.yaml. After running through steps appears to read but can't change modes (get blocking call to sleep and request never awaited)


ogger: daikinskyport
Source: custom_components/daikinskyport/daikinskyport.py:246
Integration: Daikin Skyport ([documentation](https://github.com/apetrycki/daikinskyport), [issues](https://github.com/apetrycki/daikinskyport/issues))
First occurred: 9:12:19 PM (1 occurrences)
Last logged: 9:12:19 PM
Could not refresh tokens: 400 Trying to re-request

Logger: py.warnings
Source: custom_components/daikinskyport/climate.py:580
Integration: Daikin Skyport ([documentation](https://github.com/apetrycki/daikinskyport), [issues](https://github.com/apetrycki/daikinskyport/issues))
First occurred: 9:13:57 PM (1 occurrences)
Last logged: 9:13:57 PM
/config/custom_components/daikinskyport/climate.py:580: RuntimeWarning: coroutine 'DaikinSkyport.make_request' was never awaited self.data.daikinskyport.set_away(self.thermostat_index, False)

Logger: py.warnings
Source: custom_components/daikinskyport/climate.py:730
Integration: Daikin Skyport ([documentation](https://github.com/apetrycki/daikinskyport), [issues](https://github.com/apetrycki/daikinskyport/issues))
First occurred: 9:13:57 PM (1 occurrences)
Last logged: 9:13:57 PM
/config/custom_components/daikinskyport/climate.py:730: RuntimeWarning: coroutine 'DaikinSkyport.make_request' was never awaited self.data.daikinskyport.resume_program(

 Logger: homeassistant.util.async_
Source: util/async_.py:164
First occurred: 9:13:57 PM (1 occurrences)
Last logged: 9:13:57 PM
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for daikinskyport doing blocking calls at custom_components/daikinskyport/climate.py, line 414: sleep(3)


ogger: daikinskyport
Source: custom_components/daikinskyport/daikinskyport.py:246
Integration: Daikin Skyport ([documentation](https://github.com/apetrycki/daikinskyport), [issues](https://github.com/apetrycki/daikinskyport/issues))
First occurred: 9:12:19 PM (1 occurrences)
Last logged: 9:12:19 PM
Could not refresh tokens: 400 Trying to re-request

Logger: py.warnings
Source: custom_components/daikinskyport/climate.py:580
Integration: Daikin Skyport ([documentation](https://github.com/apetrycki/daikinskyport), [issues](https://github.com/apetrycki/daikinskyport/issues))
First occurred: 9:13:57 PM (1 occurrences)
Last logged: 9:13:57 PM
/config/custom_components/daikinskyport/climate.py:580: RuntimeWarning: coroutine 'DaikinSkyport.make_request' was never awaited self.data.daikinskyport.set_away(self.thermostat_index, False)

Logger: py.warnings
Source: custom_components/daikinskyport/climate.py:730
Integration: Daikin Skyport ([documentation](https://github.com/apetrycki/daikinskyport), [issues](https://github.com/apetrycki/daikinskyport/issues))
First occurred: 9:13:57 PM (1 occurrences)
Last logged: 9:13:57 PM
/config/custom_components/daikinskyport/climate.py:730: RuntimeWarning: coroutine 'DaikinSkyport.make_request' was never awaited self.data.daikinskyport.resume_program(

 Logger: homeassistant.util.async_
Source: util/async_.py:164
First occurred: 9:13:57 PM (1 occurrences)
Last logged: 9:13:57 PM
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for daikinskyport doing blocking calls at custom_components/daikinskyport/climate.py, line 414: sleep(3)

**Comment by apetrycki** [comment]
should be fixed now.  I made a major oops

**Comment by enkrypt3d** [comment]
Much better thank you!
