### ISSUE TITLE
After update to newest version receiving cannot refresh token errors

### ISSUE THREAD

**Issue by rbkdata** [apetrycki/daikinskyport#73]
I upgrade to the newest version of Skyport.
Reinstalled integration through UI.
Rebooted
I removed the Skyport portion of the configuration.yaml
I removed the daikinskyport.conf file
Rebooted

Recieved the following errors

This error originated from a custom integration.

Logger: daikinskyport
Source: custom_components/daikinskyport/daikinskyport.py:127
Integration: Daikin Skyport (documentation, issues)
First occurred: 14:28:16 (1 occurrences)
Last logged: 14:28:16

Could not refresh tokens: 400 Trying to re-request

And then

This error originated from a custom integration.

Logger: daikinskyport
Source: custom_components/daikinskyport/daikinskyport.py:128
Integration: Daikin Skyport (documentation, issues)
First occurred: 14:28:17 (1 occurrences)
Last logged: 14:28:17

Error while requesting tokens from daikinskyport.com. Status code: 400

and finally

This error originated from a custom integration.

Logger: custom_components.daikinskyport
Source: custom_components/daikinskyport/__init__.py:79
Integration: Daikin Skyport (documentation, issues)
First occurred: 14:28:17 (1 occurrences)
Last logged: 14:28:17

Error refreshing Daikin Skyport tokens

After reboot daikinskyport.conf was not created

Can you please help me figure out where I am going wrong?

**Comment by apetrycki** [comment]
The conf file isn't used anymore. Try requesting the tokens manually with the commands in the API documentation and see if you get the same error. This should only happen if your email or password is wrong. The debug log will show you what email address is being used. The password is stored in the .storage/core.config_entries along with the saved email.

**Comment by apetrycki** [comment]
Since it's been a few days, I'm assuming you figured this out.

**Comment by rbkdata** [comment]
Thanks!  I finally had a few minutes to play around with this.  You must delete the old config.yaml entry before creating the integration.  I deleted the integration entry that was made before the config.  The yaml entry was deleted.  I deleted the config.yaml skyport section, rebooted HA and then created a new integration entry.  That worked.  Thanks!
