### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by traveler2100** [apetrycki/daikinskyport#74]
Getting the following error after upgrade to the latest version.  Completely removed and reinstalled again through HACS without success. Running Hass.io

Home Assistant 2023.8.4
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230802.1 - latest
 
Unable to prepare setup for platform daikinskyport.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
2:04:01 PM – (ERROR) setup.py

**Comment by apetrycki** [comment]
Can't really tell what the issue is without the full error.

**Comment by knightjoel** [comment]
Does the newest version of daikinskyport require HA 2023.9 or later?

In 2023.9, `DeviceInfo` is a class in `homeassistant.helpers.device_registry` but it's not in prior versions.

**Comment by traveler2100** [comment]
It may be the version, I had trouble with another integration a couple weeks ago with 9.2 so I rolled it back. Maybe this will help:

Logger: homeassistant.config_entries
Source: config_entries.py:655
First occurred: 8:40:28 PM (1 occurrences)
Last logged: 8:40:28 PM

Error unloading entry my home for daikinskyport
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 544, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/__init__.py", line 109, in async_unload_entry
    hass.data[DOMAIN][entry.entry_id][UNDO_UPDATE_LISTENER]()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 655, in <lambda>
    return lambda: self.update_listeners.remove(listener)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: list.remove(x): x not in list

**Comment by traveler2100** [comment]
I worked out an issue with another integration and upgraded to 2023.9.3 and everything is working well.  I like the update.  Thanks

Home Assistant 2023.9.3
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

**Comment by apetrycki** [comment]
> Does the newest version of daikinskyport require HA 2023.9 or later?
> 
> In 2023.9, `DeviceInfo` is a class in `homeassistant.helpers.device_registry` but it's not in prior versions.

Not sure.  It may have been moved from somewhere else.  I built the latest code around 2023.9.2 and didn't really care about backward compatibility.  It just needed a major overhaul.
