### ISSUE TITLE
Fan speed support

### ISSUE THREAD

**Issue by jf-navica** [apetrycki/daikinskyport#8]
I'm looking into adding fan speed support , not sure if it's been worked on or if it could be useful to anyone else?

**Comment by apetrycki** [comment]
Sure, anything to enhance the integration is welcome.

**Comment by apetrycki** [comment]
Does it do everything you wanted with the fan, or are you still working on it?

**Comment by jf-navica** [comment]
It does everything I wanted!  I was looking into getting the outside
temperature from the unit back to HA but gave up.

- J.F. -

**Comment by apetrycki** [comment]
You should already get that information in a sensor.  It should be named something like sensor.<thermostat name>_outdoor_temperature.  It should be taken from the wireless sensor near your condenser.  It comes from "tempOutdoor" in the JSON.
