### ISSUE TITLE
HACS creating Custom Repository isn't working

### ISSUE THREAD

**Issue by waynepeterson99** [apetrycki/daikinskyport#83]
I followed all the steps, I think correctly, but the repository doesn't show up the HCAS list ( or in the /config/custom_components folder when I checked in SSH). The add custom repository seems to have done something and it complains that it is already there if I try to do it twice. I did restart HA Core.

Looks to me like something is broken in HACS or I am doing something wrong which is a definite possibility.

I downloaded the daikinskyport repo from GitHub but haven't yet figured out how to copy it to/config/custom_components in my HA VM.

**Comment by apetrycki** [comment]
if you added it correctly, it should show up in your custom repository list in HACS.  If it doesn't show up there and it's saying you can't add it, something is wrong with your browser or installation of HACS/HA.
![image](https://github.com/apetrycki/daikinskyport/assets/34962392/422243d6-698f-4d21-ab01-8387284122ad)

**Comment by waynepeterson99** [comment]
My mistake, I was expecting to see the new repository in the main list of repositories but I do see it where your screenshot shows it.

In the "Install via HACS" instructions I seem to successfully complete up to and including 5. Select ADD.

My apologies if this is something basic that I haven't set up properly, but for 6. I don't see Supervisor in the sidebar to be able to Restart the Core. 

I am running Home Assistant in a VM so I entered Core Restart on the command line there and that did restart the Core but after that the new DaikinSkyport is no longer in Custom Repository.

And by the way I was very excited to find your Daikin Skyport integration because it is exactly what I want to do and I wasn't at all sure that this was going to be possible since Daikin removed the API from the One+ thermostat.

**Comment by apetrycki** [comment]
I think it's moved since the instructions were written. You should be able to go to Settings > System and in the top right, click the power icon and restart HA from there.

Sounds like an issue with your VM/HACS.  If it's disappearing after a restart, it's probably because the HACS directory is not persistent.  The VM runs HA in a docker container and that docker container should hold everything in the config directory as persistent.  You might need to ask someone with HACS or HA about that one.

Daikin removed the API?  Do you mean there is no longer a way to request a token to use their OpenAPI?

**Comment by waynepeterson99** [comment]
Yes I seem to be having an issue with HACS. After a restart the Custom Repository is gone.

But the good news is that after manually copying the Skyport files to custom_components with Samba I can find and configure the Skyport integration in HA. I entered my Daikin credentials and can now see the current temperature from the thermostat. Woohoo!

I'm new to HA so now I need to figure out how to set the target temperature. One thing that is interesting is that it almost looks like you could have temp sensors in multiple rooms. That is my biggest complaint about the Daikin One+ thermostat that I couldn't get a second sensor for a different room like the Ecobee has.

**Comment by apetrycki** [comment]
Good to hear.  I just found out that all the services were broken and updated them in the latest push, so you may want to update if you're going to use any of the services.  No one complained, so I guess most people don't use the services.

You can certainly create an automation to adjust the thermostat based on another temperature sensor.
