### ISSUE TITLE
Platform not found Error

### ISSUE THREAD

**Issue by mbhforum** [apetrycki/daikinskyport#86]
My config was working fine until I updated to the latest version. I wiped out my entire config and tried to reload it and I get the below error.  I put daikinskyport.conf with the bearer token manually as well as originally it was complaining about a bad token. 

Logger: homeassistant.setup
Source: setup.py:348
First occurred: 8:01:33 PM (3 occurrences)
Last logged: 8:01:33 PM

Unable to prepare setup for platform daikinskyport.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform daikinskyport.weather: Platform not found (cannot import name 'ATTR_FORECAST_HUMIDITY' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)).
Unable to prepare setup for platform daikinskyport.climate: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).

**Comment by apetrycki** [comment]
Looks like you're running an old version of HA.
