### ISSUE TITLE
Unable to adjust Cool and Heat setpoints via automation?

### ISSUE THREAD

**Issue by joeygray0519** [apetrycki/daikinskyport#88]
I can manually adjust cool and heating setpoints from the thermostat UI on a dashboard but why can't I adjust those same setpoints via automation? it only lets me change the mode.

**Comment by apetrycki** [comment]
You must be doing something wrong.  You need to call ```climate.set_temperature``` with ```temperature``` in your data if you're in heating or cooling mode, or ```target_temp_high``` and ```target_temp_low``` if you're in auto mode.
