### ISSUE TITLE
Depricated feature with Core 2024.1.0b2

### ISSUE THREAD

**Issue by dualtronic** [apetrycki/daikinskyport#90]
Error text: 
> Entity None (<class 'custom_components.daikinskyport.climate.Thermostat'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|TARGET_TEMPERATURE_RANGE|FAN_MODE|PRESET_MODE|AUX_HEAT: 91>

Error References this URL: 
https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

System that encountered error:
Core 2024.1.0b2
Supervisor 2023.12.1
Operating System 11.3.rc1
Frontend 20231228.0

**Comment by apetrycki** [comment]
Should be fixed with the latest update.  I'll check it when 2024.1 comes out of beta.

**Comment by dualtronic** [comment]
Fix and working. thx!
