### ISSUE TITLE
Warning message in Core 2024.2.0b1

### ISSUE THREAD

**Issue by jeffjumper** [apetrycki/daikinskyport#95]
The February beta is report a warning in the log:

```
WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.daikinskyport.climate.Thermostat'>) implements HVACMode(s): auto, heat, cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/apetrycki/daikinskyport/issues
```

**Comment by apetrycki** [comment]
Looks like those Features are only available in the beta version.  Adding them gives me an error in the latest stable.  Try adding
```
    | ClimateEntityFeature.TURN_ON
    | ClimateEntityFeature.TURN_OFF
```

after line 221 of the climate.py file and see if it gets rid of the message for you

**Comment by jeffjumper** [comment]
I added those 2 lines. Everything still seems to work fine, but the warning is still in the logs. Anything else you want me to try?

**Comment by apetrycki** [comment]
Hmm, ok. I thought they just needed the features added, but I guess it's a bit more involved. I'll have to see if there's any direction in the documentation or see what the Ecobee integration has done.

**Comment by apetrycki** [comment]
Looks like you also need to add 
```
    _enable_turn_on_off_backwards_compatibility = False
```
to line 398

**Comment by jeffjumper** [comment]
Yes, that did it. No more warning and the thermostat works fine. Thanks!
